name: build-and-test

on:
  push:
    branches: [master]

jobs:
  build-and-test:
    name: Build and test on ${{matrix.os}} in ${{matrix.build-type}} mode
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        build-type: [Debug, Release]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake --preset ${{matrix.build-type}} 

    - name: Build
      run: cmake --build --preset ${{matrix.build-type}}

    - name: Test
      run: ctest --preset ${{matrix.build-type}} 
